project:
  type: website
  output-dir: docs

website:

  search: false
  navbar:
    left:
      - href: index.qmd
        text: Resume
      - href: articles.qmd
        text: Articles
  page-footer: "Copyright 2026, Digambar Dagade"
  

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: false
    image-loading: lazy

editor: visual


