project:
  type: website
  output-dir: docs

website:

  search: false
  navbar:
    left:
      - href: index.qmd
        text: Resume
      - href: articles.qmd
        text: Articles
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: false

editor: visual


